
services:
  user-service:
    build: .
    container_name: user-service
    environment:
      - PORT=2001
      - MONGO_URI=mongodb://root:Bhaishashank@mongo-db:27017/ubereats_db?authSource=admin
      - SESSION_SECRET=ubereats-secret
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "2001:2001"
    depends_on:
      - mongo-db
    networks:
      - ubereats-network
    command: ["node", "index.js"]

  restaurant-service:
    build: .
    container_name: restaurant-service
    environment:
      - PORT=2002
      - MONGO_URI=mongodb://root:Bhaishashank@mongo-db:27017/ubereats_db?authSource=admin
      - SESSION_SECRET=ubereats-secret
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "2002:2002"
    depends_on:
      - mongo-db
    networks:
      - ubereats-network
    command: ["node", "index.js"]

  order-service:
    build: .
    container_name: order-service
    environment:
      - PORT=2003
      - MONGO_URI=mongodb://root:Bhaishashank@mongo-db:27017/ubereats_db?authSource=admin
      - SESSION_SECRET=ubereats-secret
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "2003:2003"
    depends_on:
      - mongo-db
    networks:
      - ubereats-network
    command: ["node", "index.js"]

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Bhaishashank
      - MONGO_INITDB_DATABASE=ubereats_db
    command: mongod --bind_ip_all 
    networks:
      - ubereats-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password Bhaishashank --authenticationDatabase admin --eval \"db.adminCommand('ping')\" || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  ubereats-network:
    driver: bridge
