apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mydocker05/ubereats-backend-order-service:latest
          ports:
            - containerPort: 2003
          env:
            - name: PORT
              value: "2003"
            - name: DB_HOST
              value: mysql-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: Bhaishashank
            - name: DB_NAME
              value: ubereats_db
            - name: DB_DIALECT
              value: mysql
