apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-status-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-status-consumer
  template:
    metadata:
      labels:
        app: order-status-consumer
    spec:
      containers:
        - name: order-status-consumer
          image: mansi061202/ubereats-order-status-consumer:latest
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
