apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mydocker05/ubereats-backend-order-service:latest
          ports:
            - containerPort: 2003
          env:
            - name: PORT
              value: "2003"
            - name: MONGO_URI
              value: mongodb://mongo-db:27017/ubereats_db
            - name: SESSION_SECRET
              value: ubereats-secret
            - name: FRONTEND_URL
              value: http://localhost:3000
            - name: KAFKA_BROKERS
              value: kafka:9092
          