apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2001
  type: ClusterIP  # Change to LoadBalancer if exposing outside the cluster
