apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: mydocker05/ubereats-backend-user-service:latest
          ports:
            - containerPort: 2001
          env:
            - name: PORT
              value: "2001"
            - name: MONGO_URI
              value: "mongodb://mongo-db:27017/ubereats_db"
            - name: SESSION_SECRET
              value: "ubereats-secret"
            - name: FRONTEND_URL
              value: "http://localhost:3000"
            - name: KAFKA_BROKERS
              value: "kafka:9092"
